#!/bin/sh

# symlink-index-md-to-readme-md
#
# Symlink each index.md file to its corresponding README.md file.
#
# This tool is typically useful for systems that display the files differently:
#
#   * A typical webserver directory will display the file "index.md" by default.
#
#   * A typical GitHub website page will display the file "README.md" by default.
#
# This tool helps the project developer be compatibile with both ways:
#
#   * The tool uses the file "index.md" as the source of truth.
#
#   * The tool creates (or recreates) the symlink "README.md".
#
# ## Tracking
#
# * Program: symlink-index-md-to-readme-md
# * Version: 1.1.0
# * License: GPL-2.0 OR GPL-3.0 or contact us for more
# * Created: 2022-08-06T13:53:48Z
# * Updated: 2023-03-21T13:27:52Z
# * Website: https://github.com/sixarm/symlink-index-md-to-readme-md
# * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)

set -euf

find . -name 'index.md' -print0 | 
xargs -0 dirname |
while read -r dir; do
    ( cd "$dir" && ln -sfn index.md README.md )
done
